import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preload"
          href="/fonts/IBMPlexSansThai-Regular.woff2"
          as="font"
          crossOrigin=""
        />
      </Head>
      <h1>Project : ระบบบริหารการสอนแบบเน้นผลลัพธ์การเรียนรู้</h1>
    </div>
  );
}
